# AUTOGENERATED! DO NOT EDIT! File to edit: ../lesson2.ipynb.

# %% auto 0
__all__ = ['learn', 'labels', 'predict']

# %% ../lesson2.ipynb 1
from fastai.vision.all import *

learn = load_learner("./models/which_bat_model.pkl")

labels = learn.dls.vocab

# %% ../lesson2.ipynb 4
def predict(img):
    img = PILImage.create(img)
    pred, pred_idx, probs = learn.predict(img)
    return {labels[i]: float(probs[i]) for i in range(len(labels))}

# %% ../lesson2.ipynb 5
import gradio as gr
gr.Interface(fn=predict, inputs=gr.inputs.Image(), outputs=gr.outputs.Label(num_top_classes=3)).launch(share=True)
